= Hyphen analysis for Elasticsearch

This project originally was created by Jörg Prante. This is a fork to make it compatible with ElasticSearch 6.5.3.

Original description:

This plugin for Elasticsearch can handle hyphens and other symbols in words or at word boundaries for improved search precision.

An example in english is the word `editor-in-chief`, which will be indexed as `editor-in-chief` plus `editor`, `in`, `chief`.

In other languages such as german, hyphenated words are much more common ("Bindestrichwörter").

This plugin also helps when analyzing acronyms or symbols in names because the hyphen characters is
configurable by the symbols that connect parts of a word. Also, keywords may be optionally respected.
So it is possible to index `Programming in C++` differently from `Programming in C`

== Documentation

For examples, see the link:https://jprante.github.io/elasticsearch-analysis-hyphen[documentation]

.Version compatibility
|===
|Plugin |Elasticsearch |Release date
|6.5.3  |6.5.3 |Dec 18, 2018
|===

== Installation

=== 6.5.3

Download http://www.netcorner.org/elasticsearch-analysis-hyphen-6.5.3-plugin.zip

[source]
----
./bin/elasticsearch-plugin install file:///path-to-zip-file/elasticsearch-analysis-hyphen-6.5.3-plugin.zip
----

Do not forget to restart the node after installing.

== Issues

All feedback is welcome! If you find issues, please post them at https://github.com/Thorsten4711/elasticsearch-analysis-hyphen/issues[Github]


= License

Hyphen Analysis Plugin for Elasticsearch

Copyright (C) 2016 Jörg Prante

Modifications (C) 2018 by Thorsten Jungblut

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
lim